"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LOGOUT = exports.LOGIN_FAIL = exports.LOGIN_SUCCESS = exports.AUTH_ERROR = exports.USER_LOADED = exports.REGISTER_FAIL = exports.REGISTER_SUCCESS = exports.REMOVE_ALERT = exports.SET_ALERT = void 0;
exports.SET_ALERT = 'SET_ALERT';
exports.REMOVE_ALERT = 'REMOVE_ALERT';
exports.REGISTER_SUCCESS = 'REGISTER_SUCCESS';
exports.REGISTER_FAIL = 'REGISTER_FAIL';
exports.USER_LOADED = 'USER_LOADED';
exports.AUTH_ERROR = 'AUTH_ERROR';
exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS';
exports.LOGIN_FAIL = 'LOGIN_FAIL';
exports.LOGOUT = 'LOGOUT';
